version: 2
project_name: aws-vault

source:
  enabled: false

env:
  #- GO111MODULE=on
  #- GOPROXY=https://gocenter.io

#before:
#  hooks:
#    - go mod tidy
#    - go mod vendor
#    #- go mod download

builds:
  - binary: aws-vault
    #main: ./main.go
    #goos:
    #  - linux
    #  - darwin
    #  - windows
    #goarch:
    #  - amd64
    targets:
      - linux_amd64
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
    env:
      - CGO_ENABLED=1
      - GOTELEMETRY="off"
    flags:
      - -v
    ldflags:
      - -s -w -X main.Version={{.Version}}

upx:
  - enabled: true
    #goos: [linux, windows]

archives:
  - id: aws-vault
    #builds:
    #  - aws-vault|default
    #format: zip
    #name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ["zip"]
    #replacements:
    #  darwin: Darwin
    #  linux: Linux
    #  windows: Windows
    #format: tar.gz
    #format_overrides:
    #  - goos: windows
    #    format: zip
    files:
      - none*

universal_binaries:
 - replace: true

release:
  prerelease: auto
  draft: false
  disable: false
  name_template: "v{{ .Version }}"
  footer: |
    **Full Changelog**: https://github.com/byteness/aws-vault/compare/{{ .PreviousTag }}...{{ if .IsNightly }}nightly{{ else }}{{ .Tag }}{{ end }}

milestones:
  - close: true

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha256_checksums.txt"
  algorithm: sha256

changelog:
  use: github #git # github(-native)
  sort: asc
  format: "{{ .SHA }}: {{ .Message }}{{ with .AuthorUsername }} (@{{ . }}){{ end }}"
  # Disabled when using 'github-native'.
  groups:
    - title: "🚀 New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      #regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "🔒 Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "🐛 Bug fixes"
      regexp: '^.*?(fix|refactor|bug)(\(.+\))??!?:.+$'
     # regexp: '^.*?(fix|bug)(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "📝 Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: 🎯 Other work
      order: 9999
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "^chore: update$"
      - "^chore: docs$"
      - "^docs: update$"
      - "^chore: schema$"
      - "^chore: typo$"
      - "^chore: auto-update generated files$"
      - "^chore: update schema$"
      - "^chore: schema update$"
      - "^chore\\(deps\\): "
      - "^(build|ci): "
      - "merge conflict"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - typo
